# Generated by Django 5.1.2 on 2024-10-26 22:44

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(verbose_name='описание')),
                ('app_updates', models.TextField(blank=True, null=True, verbose_name='обновления приложений')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=500, verbose_name='навзание')),
                ('name_uz', models.CharField(max_length=500, null=True, verbose_name='навзание')),
                ('name_ru', models.CharField(max_length=500, null=True, verbose_name='навзание')),
                ('name_en', models.CharField(max_length=500, null=True, verbose_name='навзание')),
                ('name_ar', models.CharField(max_length=500, null=True, verbose_name='навзание')),
            ],
            options={
                'verbose_name': 'Категория поста',
                'verbose_name_plural': 'Категория посты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, verbose_name='название')),
                ('name_uz', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('name_ru', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('name_ar', models.CharField(max_length=150, null=True, verbose_name='название')),
                ('description', models.TextField(verbose_name='описание')),
                ('description_uz', models.TextField(null=True, verbose_name='описание')),
                ('description_ru', models.TextField(null=True, verbose_name='описание')),
                ('description_en', models.TextField(null=True, verbose_name='описание')),
                ('description_ar', models.TextField(null=True, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'Глава',
                'verbose_name_plural': 'Главы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ru', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', verbose_name='файл')),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ru', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
                ('is_premium', models.BooleanField(default=False, verbose_name='это премиум')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavilot.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.CharField(max_length=150, verbose_name='элемент')),
                ('price', models.FloatField(default=0, verbose_name='цена')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'verbose_name': 'Продажa',
                'verbose_name_plural': 'Продажи',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Verse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(verbose_name='порядковый номер стиха')),
                ('text', models.TextField(verbose_name='текст')),
                ('text_uz', models.TextField(null=True, verbose_name='текст')),
                ('text_ru', models.TextField(null=True, verbose_name='текст')),
                ('text_en', models.TextField(null=True, verbose_name='текст')),
                ('text_ar', models.TextField(null=True, verbose_name='текст')),
                ('text_arabic', models.TextField(verbose_name='текст на арабском языке')),
                ('description', models.TextField(verbose_name='описание')),
                ('description_uz', models.TextField(null=True, verbose_name='описание')),
                ('description_ru', models.TextField(null=True, verbose_name='описание')),
                ('description_en', models.TextField(null=True, verbose_name='описание')),
                ('description_ar', models.TextField(null=True, verbose_name='описание')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavilot.chapter', verbose_name='глава')),
            ],
            options={
                'verbose_name': 'Стих',
                'verbose_name_plural': 'Стихи',
                'ordering': ('-created_at',),
            },
        ),
    ]
