# Generated by Django 5.1.2 on 2024-10-29 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0002_sheikh_audio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('-created_at',), 'verbose_name': 'Сура', 'verbose_name_plural': 'Суры'},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ('-created_at',), 'verbose_name': 'Айат', 'verbose_name_plural': 'Айаты'},
        ),
        migrations.RemoveField(
            model_name='aboutus',
            name='app_updates',
        ),
        migrations.AlterField(
            model_name='post',
            name='is_premium',
            field=models.BooleanField(default=False, verbose_name='премиум'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='chapter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tavilot.chapter', verbose_name='сура'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='number',
            field=models.PositiveIntegerField(verbose_name='порядковый номер айат'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.TextField(verbose_name='айат'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_ar',
            field=models.TextField(null=True, verbose_name='айат'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_arabic',
            field=models.TextField(verbose_name='айат на арабском языке'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_en',
            field=models.TextField(null=True, verbose_name='айат'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_ru',
            field=models.TextField(null=True, verbose_name='айат'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_uz',
            field=models.TextField(null=True, verbose_name='айат'),
        ),
    ]
