# Generated by Django 5.1.2 on 2024-10-29 18:53

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0003_alter_chapter_options_alter_verse_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name_ru',
            new_name='name_kr',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='description_ru',
            new_name='description_kr',
        ),
        migrations.RenameField(
            model_name='chapter',
            old_name='name_ru',
            new_name='name_kr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='description_ru',
            new_name='description_kr',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title_ru',
            new_name='title_kr',
        ),
        migrations.RenameField(
            model_name='verse',
            old_name='description_ru',
            new_name='description_kr',
        ),
        migrations.RenameField(
            model_name='verse',
            old_name='text_ru',
            new_name='text_kr',
        ),
        migrations.AddField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=500, null=True, verbose_name='навзание'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='name_tr',
            field=models.CharField(max_length=150, null=True, verbose_name='название'),
        ),
        migrations.AddField(
            model_name='post',
            name='description_tr',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_tr',
            field=models.CharField(max_length=300, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='verse',
            name='description_tr',
            field=models.TextField(null=True, verbose_name='описание'),
        ),
        migrations.AddField(
            model_name='verse',
            name='text_tr',
            field=models.TextField(null=True, verbose_name='айат'),
        ),
    ]
