# Generated by Django 5.1.2 on 2024-11-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0007_post_image_alter_post_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verse',
            name='number',
            field=models.PositiveIntegerField(db_index=True, verbose_name='порядковый номер аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text',
            field=models.TextField(db_index=True, verbose_name='аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_ar',
            field=models.TextField(db_index=True, null=True, verbose_name='аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_arabic',
            field=models.TextField(db_index=True, verbose_name='айат на арабском языке'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_en',
            field=models.TextField(db_index=True, null=True, verbose_name='аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_kr',
            field=models.TextField(db_index=True, null=True, verbose_name='аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_tr',
            field=models.TextField(db_index=True, null=True, verbose_name='аят'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='text_uz',
            field=models.TextField(db_index=True, null=True, verbose_name='аят'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['number'], name='number_index'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['text'], name='text_index'),
        ),
        migrations.AddIndex(
            model_name='verse',
            index=models.Index(fields=['text_arabic'], name='text_arabic_index'),
        ),
    ]
