# Generated by Django 5.1.2 on 2024-11-08 02:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0008_alter_verse_number_alter_verse_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_kr',
            field=models.CharField(max_length=255, null=True, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='навзание'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='навзание'),
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('name_uz', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_tr', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('name_kr', models.CharField(max_length=255, null=True, verbose_name='название')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_subcategory', to='tavilot.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Подкатегория',
                'verbose_name_plural': 'Подкатегории',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddField(
            model_name='post',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tavilot.subcategory', verbose_name='подкатегория'),
        ),
    ]
