# Generated by Django 5.1.2 on 2024-11-08 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0009_alter_category_name_alter_category_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audio',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='sheikh',
        ),
        migrations.RemoveField(
            model_name='audio',
            name='verse',
        ),
        migrations.DeleteModel(
            name='Sheikh',
        ),
        migrations.DeleteModel(
            name='Audio',
        ),
    ]
