# Generated by Django 5.1.2 on 2024-11-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0010_juz_remove_audio_chapter_remove_audio_sheikh_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='name_arabic',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='название на арабском языке'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='verse_number',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='количество аятов'),
        ),
    ]
