# Generated by Django 5.1.2 on 2024-11-11 15:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0010_remove_audio_chapter_remove_audio_sheikh_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Juz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.PositiveIntegerField(unique=True)),
                ('title', models.CharField(max_length=500)),
                ('title_uz', models.CharField(max_length=500, null=True)),
                ('title_tr', models.CharField(max_length=500, null=True)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_ar', models.CharField(max_length=500, null=True)),
                ('title_kr', models.CharField(max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'Джуз',
                'verbose_name_plural': 'Джузы',
                'ordering': ['number'],
            },
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('number',), 'verbose_name': 'Сура', 'verbose_name_plural': 'Суры'},
        ),
        migrations.AlterModelOptions(
            name='verse',
            options={'ordering': ('number',), 'verbose_name': 'Аят', 'verbose_name_plural': 'Аяты'},
        ),
        migrations.AddField(
            model_name='chapter',
            name='number',
            field=models.PositiveIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chapter',
            name='juz',
            field=models.ManyToManyField(related_name='juz_chapter', to='tavilot.juz', verbose_name='джуз'),
        ),
        migrations.AddField(
            model_name='verse',
            name='juz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='juz_verse', to='tavilot.juz', verbose_name='джуз'),
            preserve_default=False,
        ),
    ]
