# Generated by Django 5.1.2 on 2024-11-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0011_chapter_name_arabic_chapter_verse_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='type_choice',
            field=models.IntegerField(blank=True, choices=[(1, 'Makkiy'), (2, 'Madaniy')], null=True, verbose_name='место ниспослания суры'),
        ),
    ]
