# Generated by Django 5.1.2 on 2024-11-22 02:34

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0012_chapter_type_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_ar',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_kr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_tr',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_uz',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='заголовок'),
        ),
        migrations.AddField(
            model_name='post',
            name='file_type',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description_ar',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description_kr',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description_tr',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='описание аята'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description_ar',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание аята'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание аята'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description_kr',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание аята'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description_tr',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание аята'),
        ),
        migrations.AlterField(
            model_name='verse',
            name='description_uz',
            field=tinymce.models.HTMLField(null=True, verbose_name='описание аята'),
        ),
    ]
