# Generated by Django 5.1.2 on 2024-12-11 13:49

import django.core.validators
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0013_category_title_category_title_ar_category_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manuscript',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_kr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='файл')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_tr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_kr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Рукопись и комментарии',
                'verbose_name_plural': 'Рукописи и комментарии',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Moturudiy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_kr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='файл')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_tr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_kr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Мотуруди',
                'verbose_name_plural': 'Мотуруди',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Refusal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_kr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='файл')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_tr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_kr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Опровержение фанатизма',
                'verbose_name_plural': 'Опровержение фанатизма',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Resources',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_kr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='файл')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_tr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_kr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Studies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=300, verbose_name='заголовок')),
                ('title_uz', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_tr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_en', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_ar', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('title_kr', models.CharField(max_length=300, null=True, verbose_name='заголовок')),
                ('file', models.FileField(blank=True, null=True, upload_to='to_students/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='файл')),
                ('file_type', models.CharField(blank=True, max_length=10, null=True)),
                ('description', tinymce.models.HTMLField(verbose_name='описание')),
                ('description_uz', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_tr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_en', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_ar', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('description_kr', tinymce.models.HTMLField(null=True, verbose_name='описание')),
                ('is_published', models.BooleanField(default=False, verbose_name='опубликовано')),
            ],
            options={
                'verbose_name': 'Исследовать',
                'verbose_name_plural': 'Исследования',
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='sub_category',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='user',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='SubCategory',
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
