# Generated by Django 5.1.2 on 2024-12-13 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tavilot', '0014_manuscript_moturudiy_refusal_resources_studies_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refusal',
            name='file',
        ),
        migrations.RemoveField(
            model_name='refusal',
            name='file_type',
        ),
        migrations.AddField(
            model_name='refusal',
            name='youtube_url',
            field=models.URLField(default='https://www.youtube.com/', verbose_name='ютуб адрес'),
        ),
    ]
