# Generated by Django 5.1.2 on 2024-10-26 22:44

import authentication.utils
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('phone_number', models.CharField(validators=[authentication.utils.phone_number_validation], verbose_name='Номер телефона')),
                ('password', models.CharField(max_length=125, verbose_name='Пороль')),
                ('email', models.CharField(max_length=125, verbose_name='Электронная почта')),
                ('rate', models.PositiveIntegerField(choices=[(1, 'Base'), (2, 'Pro')], default=1, verbose_name='тариф')),
                ('first_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=125, null=True, verbose_name='Фамилия')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Проверено')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('otp_code', models.IntegerField(default=authentication.utils.generate_otp_code)),
                ('otp_key', models.UUIDField(default=uuid.uuid4)),
                ('attempts', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
