# Generated by Django 5.1.2 on 2024-10-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_options_otp_otp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время входа'),
        ),
    ]
