# Generated by Django 5.1.2 on 2024-11-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_remove_otp_otp_token_resettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=125, null=True, verbose_name='Электронная почта'),
        ),
    ]
