# Generated by Django 5.1.2 on 2024-11-29 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_remove_user_email'),
        ('pyment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payme_id', models.CharField(max_length=100)),
                ('amount', models.PositiveIntegerField()),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('perform_time', models.DateTimeField(blank=True, null=True)),
                ('cancel_time', models.DateTimeField(blank=True, null=True)),
                ('state', models.IntegerField(choices=[(1, 'Pending'), (2, 'Completed'), (-1, 'Cancelled'), (-2, 'Timeout Cancelled')], default=1)),
                ('reason', models.IntegerField(blank=True, null=True)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pyment.subscription')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CreateTransaction',
        ),
    ]
