# Generated by Django 5.1.2 on 2024-12-03 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyment', '0002_transaction_delete_createtransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_trans_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('click_paydoc_id', models.CharField(max_length=100)),
                ('merchant_trans_id', models.CharField(max_length=255, verbose_name='User id')),
                ('amount', models.FloatField()),
                ('error', models.IntegerField(blank=True, null=True)),
                ('error_note', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_time', models.CharField(max_length=255)),
                ('sign_string', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Prepare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_trans_id', models.CharField(max_length=100)),
                ('service_id', models.CharField(max_length=100)),
                ('click_paydoc_id', models.CharField(max_length=100)),
                ('merchant_trans_id', models.CharField(max_length=255, verbose_name='User id')),
                ('amount', models.FloatField()),
                ('error', models.IntegerField(blank=True, null=True)),
                ('error_note', models.CharField(blank=True, max_length=255, null=True)),
                ('sign_time', models.CharField(max_length=255)),
                ('sign_string', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('click_trans_id', models.CharField(max_length=100)),
                ('status', models.IntegerField(choices=[(0, 'Prepare'), (1, 'Complete')], default=0)),
                ('complete', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='pyment.complete')),
                ('prepare', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyment.prepare')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='complete',
            name='merchant_prepare_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pyment.prepare'),
        ),
    ]
